language: node_js
node_js: 8
dist: trusty

services:
  - docker

addons:
  apt:
    packages:
      - bash
      - git
      - dbus
      - dbus-x11
      - xvfb
      - make
      - g++
      - libnss3
      - libasound2
      - libgconf-2-4
      - libxtst6
      - libxss1
      - libgtk2.0-0

env:
  global:
    - API_HOST=172.17.0.1
    - REDIS_URL=redis://172.17.0.1:6379   # we'll pick up openwhisk's redis
    - UV_THREADPOOL_SIZE=128
    - NO_NOTIFICATIONS=true
    - NO_DEBUGGER_BREAKPOINTS=true
    - WINDOW_WIDTH=1400
    - WINDOW_HEIGHT=1050
    - KEY_FROM_LAYER=true
    - DISPLAY=:99

install:
    - echo "API_HOST=foo" > ~/.wskprops                                                  # dist/compile.sh needs something here
    - echo "AUTH=bar" >>  ~/.wskprops                                                    # ibid
    - (cd app && npm install) &                                                          # app npm install
    - (cd tests && npm install) &                                                        # tests npm install
    - (./tools/travis/setup.sh; ./tools/travis/build.sh; ./tools/travis/init_auth.sh) &  # initialize openwhisk and test docker
    - wait
    - Xvfb $DISPLAY -screen 0 ${WINDOW_WIDTH}x${WINDOW_HEIGHT}x24 -ac &
    - sleep 5
#    - rm .dockerignore
#    - cp tools/travis/Dockerfile .
#    - docker build -t shell-test .                                                       # initialize test docker image

#script: (cd tests && npm run test)
#script: (cd tests && ./bin/runLocal.sh 01 08 07 02 03 04 05)

jobs:
  include:
    - script: (cd tests && ./bin/runLocal.sh)
      env: LAYER=01
    - script: (cd tests && ./bin/runLocal.sh)
      env: LAYER=08
    - script: (cd tests && ./bin/runLocal.sh)
      env: LAYER=07
    - script: (cd tests && ./bin/runLocal.sh)
      env: LAYER=02
    - script: (cd tests && ./bin/runLocal.sh)
      env: LAYER=03
    - script: (cd tests && ./bin/runLocal.sh)
      env: LAYER=04
    - script: (cd tests && ./bin/runLocal.sh)
      env: LAYER=05
